spring:
  application:
    name: identity-access-management-service

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
 #  username: identityservice7@gmail.com
 #  password: ztedjgmffwlwdhta
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true

  datasource:
    url: jdbc:mysql://db:3306/authxdb?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate.format_sql: true
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect

  # ✅ NEW: use local Memurai/Redis
  data:
    redis:
      host: redis
      port: 6379

server:
  port: 8080

jwt:
  secret: ${JWT_SECRET:devDefaultSecretKeyMakeThisVeryLongAndSecure123!}
  access-token-expiration-ms: 3600000
  refresh-token-expiration-ms: 2592000000

logging:
  level:
    com.portfolio.auth: DEBUG
